# WEEK2 E1

author name: Keerthan kumar c 
class: III Sem Btech DSE Section B
Batch:B1
Roll no: 2 
Reg no:220968002

# Exercise 1 â€“ Data Preprocessing Using the given CEREALS dataset, perform data preprocessing and answer the following questions.

# 1) Create a table with the 5-number summary of all the numeric attributes

In [22]:
import pandas as pd
import numpy as np

In [4]:
!pip install xlrd

Collecting xlrd
  Using cached xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000021350BA5FC0>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host')': /simple/xlrd/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000021350BA62C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/xlrd/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000021350BA65F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/xlrd/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000021350BA67A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/xlrd/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000021350BA6950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/xlrd/

In [23]:
df=pd.read_excel("Cereals1.xls")
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
1,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
2,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
3,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
4,Apple_Cinnamon_Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
72,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
73,Wheat_Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
74,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
75,Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [24]:
print("5-number summary of all the numeric attributes is:")
df.describe()

5-number summary of all the numeric attributes is:

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,107.368421,2.526316,1.013158,160.065789,2.048684,14.723684,6.934211,93.657895,28.289474,2.197368,1.030000,0.827500,42.327057
std,19.139378,1.089020,1.013159,84.318813,2.219038,4.160444,4.473136,68.502565,22.487813,0.832982,0.151438,0.227204,13.820602
min,50.000000,1.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,132.500000,0.750000,12.000000,3.000000,40.000000,25.000000,1.000000,1.000000,0.670000,32.932466
50%,110.000000,2.500000,1.000000,180.000000,1.750000,14.500000,7.000000,90.000000,25.000000,2.000000,1.000000,0.750000,40.253086
75%,110.000000,3.000000,2.000000,212.500000,3.000000,17.000000,11.000000,120.000000,25.000000,3.000000,1.000000,1.000000,50.780847
max,160.000000,6.000000,5.000000,320.000000,14.000000,23.000000,15.000000,330.000000,100.000000,3.000000,1.500000,1.500000,93.704912

# 2)For each of the numeric attributes (proteins up to vitamins), identify and replace all missing data (indicated with -1) with the arithmetic mean of the attribute.

In [25]:
for c in df.columns:
    if(c=="protein" or c=="fat" or c=="sodium" or c=="fiber" or c=="carbo" or c=="sugars" or c=="potass" or c=="vitamins"):
        mean=df[c].mean()
        df[c].replace(to_replace=-1, value=mean, inplace=True)
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,135.000000,0,3,1.0,1.00,33.983679
1,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,320.000000,25,3,1.0,0.33,59.425505
2,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.000000,25,3,1.0,0.50,93.704912
3,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,93.657895,25,3,1.0,0.75,34.384843
4,Apple_Cinnamon_Cheerios,G,C,110,2,2,180,1.5,10.5,10.0,70.000000,25,1,1.0,0.75,29.509541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Triples,G,C,110,2,1,250,0.0,21.0,3.0,60.000000,25,3,1.0,0.75,39.106174
72,Trix,G,C,110,1,1,140,0.0,13.0,12.0,25.000000,25,2,1.0,1.00,27.753301
73,Wheat_Chex,R,C,100,3,1,230,3.0,17.0,3.0,115.000000,25,1,1.0,0.67,49.787445
74,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,110.000000,25,1,1.0,1.00,51.592193
75,Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8.0,60.000000,25,1,1.0,0.75,36.187559

# Create a table with the 5-number summary of all the numeric attributes after treating missing values. Do you think the strategy used in dealing with missing values was effective?

In [26]:
df.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,107.368421,2.526316,1.013158,160.065789,2.048684,14.930575,7.038608,96.148892,28.289474,2.197368,1.030000,0.827500,42.327057
std,19.139378,1.089020,1.013159,84.318813,2.219038,3.737575,4.377048,66.688658,22.487813,0.832982,0.151438,0.227204,13.820602
min,50.000000,1.000000,0.000000,0.000000,0.000000,7.000000,0.000000,15.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,132.500000,0.750000,12.000000,3.000000,43.750000,25.000000,1.000000,1.000000,0.670000,32.932466
50%,110.000000,2.500000,1.000000,180.000000,1.750000,14.861842,7.000000,90.000000,25.000000,2.000000,1.000000,0.750000,40.253086
75%,110.000000,3.000000,2.000000,212.500000,3.000000,17.000000,11.000000,120.000000,25.000000,3.000000,1.000000,1.000000,50.780847
max,160.000000,6.000000,5.000000,320.000000,14.000000,23.000000,15.000000,330.000000,100.000000,3.000000,1.500000,1.500000,93.704912

yes,the strategy used was helpful as it gave us a necessary output

# For each of the numeric attributes (proteins up to vitamins), identify and replace all noisy data with the median of attribute.

In [28]:
for c in df.columns:
    if(c=="protein" or c=="fat" or c=="sodium" or c=="fiber" or c=="carbo" or c=="sugars" or c=="potass" or c=="vitamins"):
        q3=df[c].quantile(0.75)
        q1=df[c].quantile(0.25)
        iqr=q3-q1
        uth=q3+(1.5*iqr)
        lth=q1-(1.5*iqr)
        median1=df[c].median()
        df[c]=df[c].apply(lambda x:median1 if x>uth or x<lth else x)
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100%_Natural_Bran,Q,C,120,3.0,5,180.0,2.00,8.0,8.0,135.000000,25.0,3,1.0,1.00,33.983679
1,All-Bran,K,C,70,4.0,1,260.0,1.75,7.0,5.0,90.000000,25.0,3,1.0,0.33,59.425505
2,All-Bran_with_Extra_Fiber,K,C,50,4.0,0,140.0,1.75,8.0,0.0,90.000000,25.0,3,1.0,0.50,93.704912
3,Almond_Delight,R,C,110,2.0,2,200.0,1.00,14.0,8.0,93.657895,25.0,3,1.0,0.75,34.384843
4,Apple_Cinnamon_Cheerios,G,C,110,2.0,2,180.0,1.50,10.5,10.0,70.000000,25.0,1,1.0,0.75,29.509541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Triples,G,C,110,2.0,1,250.0,0.00,21.0,3.0,60.000000,25.0,3,1.0,0.75,39.106174
72,Trix,G,C,110,1.0,1,140.0,0.00,13.0,12.0,25.000000,25.0,2,1.0,1.00,27.753301
73,Wheat_Chex,R,C,100,3.0,1,230.0,3.00,17.0,3.0,115.000000,25.0,1,1.0,0.67,49.787445
74,Wheaties,G,C,100,3.0,1,200.0,3.00,17.0,3.0,110.000000,25.0,1,1.0,1.00,51.592193
75,Wheaties_Honey_Gold,G,C,110,2.0,1,200.0,1.00,16.0,8.0,60.000000,25.0,1,1.0,0.75,36.187559

# Create a table with the 5-number summary of all the numeric attributes after treating noisy values. Do you think the strategy used in dealing with noisy values was effective?

In [29]:
df.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.0,76.000000,76.000000,76.000000,76.000000
mean,107.368421,2.401316,1.013158,185.657895,1.792105,14.930575,7.038608,83.912050,25.0,2.197368,1.030000,0.827500,42.327057
std,19.139378,0.875670,1.013159,48.595899,1.520220,3.737575,4.377048,45.034796,0.0,0.832982,0.151438,0.227204,13.820602
min,50.000000,1.000000,0.000000,70.000000,0.000000,7.000000,0.000000,15.000000,25.0,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,157.500000,0.750000,12.000000,3.000000,43.750000,25.0,1.000000,1.000000,0.670000,32.932466
50%,110.000000,2.250000,1.000000,180.000000,1.625000,14.861842,7.000000,90.000000,25.0,2.000000,1.000000,0.750000,40.253086
75%,110.000000,3.000000,2.000000,210.000000,3.000000,17.000000,11.000000,110.000000,25.0,3.000000,1.000000,1.000000,50.780847
max,160.000000,4.000000,5.000000,290.000000,6.000000,23.000000,15.000000,200.000000,25.0,3.000000,1.500000,1.500000,93.704912

yes,the method is effective as we can see the output